[package]
name = "pacman-parallelizer2"
version = "0.1.0"
authors = ["lestofante <lestofante88@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fork = "0.1"